// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eCommercePortal.Domain.Entites;
using eCommercePortal.Repository.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace eCommercePortal.Repository.Models.Configurations
{
    public partial class TransactionConfiguration : IEntityTypeConfiguration<Transaction>
    {
        public void Configure(EntityTypeBuilder<Transaction> entity)
        {
            entity.HasKey(e => e.TransactionId).HasName("PK__Transact__55433A4B18119739");

            entity.Property(e => e.TransactionId).HasColumnName("TransactionID");
            entity.Property(e => e.Amount).HasColumnType("money");
            entity.Property(e => e.CustomerMobileNumber)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("Customer_MobileNumber");
            entity.Property(e => e.GroceryName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Quantity).HasColumnType("decimal(6, 2)");
            entity.Property(e => e.RewardPoints).HasColumnType("decimal(6, 2)");

            entity.HasOne(d => d.CustomerMobileNumberNavigation).WithMany(p => p.Transactions)
                .HasForeignKey(d => d.CustomerMobileNumber)
                .HasConstraintName("FK__Transacti__Custo__38996AB5");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Transaction> entity);
    }
}
