// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eCommercePortal.Domain.Entites;
using eCommercePortal.Repository.Models.Configurations;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable disable

namespace eCommercePortal.Repository.Models;

public partial class eCommerceContext : DbContext
{
    public eCommerceContext(DbContextOptions<eCommerceContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Transaction> Transactions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.CustomerConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TransactionConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
