// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eCommercePortal.Domain.Entites;

public partial class Customer
{
    public string MobileNumber { get; set; }

    public string CustomerName { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}