// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eCommercePortal.Domain.Entites;

public partial class Transaction
{
    public int TransactionId { get; set; }

    public string CustomerMobileNumber { get; set; }

    public string GroceryName { get; set; }

    public decimal? Amount { get; set; }

    public decimal? Quantity { get; set; }

    public decimal? RewardPoints { get; set; }
    public DateTime TransactionDate { get; set; }

    public virtual Customer CustomerMobileNumberNavigation { get; set; }
}